##
## SPRING BOOT SETTINGS
##

server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

##
## DATABASE SETTINGS
##

database:
  # what CRS persisted geometries do have
  srid: EPSG:4326
  jpa:
    persistence-location: "classpath:META-INF/persistence.xml"

spring:
  main:
    allow-circular-references: true
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/proxy
    initialization-mode: always
  jpa:
    properties:
      hibernate: 
        hbm2ddl:
          # hbm2ddl values: validate | update | create | create-drop
          auto: update
        jdbc:
          time_zone: UTC
          # https://hibernate.atlassian.net/browse/HHH-12368
          lob.non_contextual_creation: true
        format_sql: false
        default_schema: public
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

        # disable driver's feature detection
        # see https://stackoverflow.com/questions/46493500/hibernate-with-c3p0-createclob-is-not-yet-implemented
        temp.use_jdbc_metadata_defaults: false

##
## LOGGING SETTINGS
##
debug: false
logging:
  # config: classpath:logback.xml
  level:
    root: ERROR
    org.n52: INFO
    ## Spring
    #org.springframework: INFO
    #org.springframework.web.servlet.mvc.method.annotation: INFO
    ## Hibernate
    #org.hibernate: INFO
    #org.hibernate.type: TRACE
    #org.hibernate.SQL: DEBUG
    ## other
    #org.apache: WARN
    #org.geotools: WARN
    #com.sun.xml: ERROR




## Service Configuration
service:
  config:
    file: /hereon/hereon-config.json
  connector:
    # hereon config
    hereon:
      mapping:
        file: /hereon/mapping.json
      # username: 
      # password: 
      # url:
      #	  service: 
      #	  token: 
      # job:
      #   cron: 
